/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterPage;

import static InterPage.Register.em;
import static InterPage.Register.usname;
import Logs.Login;
import dbConnect.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import table.U_Admin;

/**
 *
 * @author Windows 10
 */
public class CreateUserForm extends javax.swing.JFrame {

    /**
     * Creates new form ChangesPassword
     */
    public CreateUserForm() {
        initComponents();
    }
   
      
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        stats = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        stats1 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        stats2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        dob1 = new javax.swing.JLabel();
        password1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cnum = new javax.swing.JTextField();
        IID = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Creat User Form");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 300, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 50));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 170, -1));

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setText("FIRSTNAME:");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 20));

        LastName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LastName.setText("LASTNAME:");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, 20));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 170, -1));

        user.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user.setText("USERNAME:");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        dob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dob.setText("CONFIRM PASSWORD :");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, -1));

        register.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 100, 30));

        stats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        stats.setText("USER STATUS :");
        getContentPane().add(stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 110, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 170, -1));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 170, -1));

        stats1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        stats1.setText("EMAIL:");
        getContentPane().add(stats1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 170, -1));

        stats2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        stats2.setText("ACCOUNT TYPE :");
        getContentPane().add(stats2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 100, 30));

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 100, 30));

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 100, 30));

        remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 100, 30));

        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 100, 30));

        refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 100, 30));

        dob1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dob1.setText("PASSWORD:");
        getContentPane().add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("PHONENUMBER:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        cnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnumActionPerformed(evt);
            }
        });
        getContentPane().add(cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, -1));

        IID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IIDActionPerformed(evt);
            }
        });
        getContentPane().add(IID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 170, -1));

        name1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name1.setText("USER ID :");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 90, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        if(fname.getText().isEmpty() || lname.getText().isEmpty() || email.getText().isEmpty() || username.getText().isEmpty()
                || password.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(password.getText().length() < 8){
            JOptionPane.showMessageDialog(null, "Characters password is 8 above!");
            password.setText(""); 
        }else if(!isValidEmail(email.getText())){
            JOptionPane.showMessageDialog(null, "Invalid Email");
        } else if (!isNumeric(cnum.getText())) {
             JOptionPane.showMessageDialog(null, "Contact number must contain only numbers.");
        }else if(cnum.getText().length() > 15 || cnum.getText().length() < 11)
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone num");
        }else{

            dbConnector dbc = new dbConnector();

            if (dbc.insertData("INSERT INTO user(i_fname, i_lname, i_username, i_password, i_email, i_phonenumber, i_type, status) "
                + "VALUES('" + fname.getText() + "', '" + lname.getText() + "', '"
                + username.getText() + "', '" + password.getText() + "', '"
                + email.getText() + "','" + cnum.getText() + "', '" + type.getSelectedItem().toString() + "', 'PENDING')")) {
            JOptionPane.showMessageDialog(null, "Register Successfully");

            JOptionPane.showMessageDialog(null, "Inserted Successfully!");
            Login ads = new Login();
            ads.setVisible(true);
            this.dispose(); 

        }else{
            JOptionPane.showMessageDialog(null, "Connection Error!");
        }
        }
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
      
    }//GEN-LAST:event_registerActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            U_Admin ua = new U_Admin();
            ua.setVisible(true);
            this.dispose();         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      if(fname.getText().isEmpty() || lname.getText().isEmpty() || email.getText().isEmpty() || username.getText().isEmpty()
                || password.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if(password.getText().length() < 8){
            JOptionPane.showMessageDialog(null, "Characters password is 8 above!");
            password.setText(""); 
        }else if(!isValidEmail(email.getText())){
            JOptionPane.showMessageDialog(null, "Invalid Email");
        } else if (!isNumeric(cnum.getText())) {
             JOptionPane.showMessageDialog(null, "Contact number must contain only numbers.");
        }else if(cnum.getText().length() > 15 || cnum.getText().length() < 11)
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone num");
        }else{

            dbConnector dbc = new dbConnector();

           dbc.updateData("UPDATE user Set i_fname = '" + fname.getText() + "', i_lname =  '" + lname.getText() + "', i_username = '"+ username.getText() + "'"
                   + ", i_password = '" + password.getText() + "', i_email = '"+ email.getText() + "', i_phonenumber = '" + cnum.getText() + "', i_type = '" + type.getSelectedItem().toString() + "', "
                           + "status = '" + status.getSelectedItem().toString() + "'");
             
            

            
            U_Admin ua = new U_Admin();
            ua.setVisible(true);
            this.dispose(); 

        
        } 
    }//GEN-LAST:event_updateActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password1ActionPerformed

    private void cnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnumActionPerformed

    private void IIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField IID;
    private javax.swing.JLabel LastName;
    public javax.swing.JButton add;
    private javax.swing.JButton clear;
    public javax.swing.JTextField cnum;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel dob1;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fname;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField lname;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    public javax.swing.JTextField password;
    public javax.swing.JTextField password1;
    private javax.swing.JButton refresh;
    private javax.swing.JButton register;
    private javax.swing.JButton remove;
    private javax.swing.JLabel stats;
    private javax.swing.JLabel stats1;
    private javax.swing.JLabel stats2;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JComboBox<String> type;
    public javax.swing.JButton update;
    private javax.swing.JLabel user;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
private boolean isValidEmail(String text) {
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    Pattern pattern = Pattern.compile(regex);
    Matcher matcher = pattern.matcher(text);
    return matcher.matches();

    }
    
    private boolean isNumeric(String text) {
        try {
        Double.parseDouble(text);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
    }

}
