/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalPage;

/**
 *
 * @author Windows 10
 */
public class Register extends javax.swing.JInternalFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LName = new javax.swing.JTextField();
        Pnumber = new javax.swing.JTextField();
        User = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Password1 = new javax.swing.JPasswordField();
        Password2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        Confirm = new javax.swing.JButton();
        Cancel1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpanel2.setBackground(new java.awt.Color(102, 255, 255));
        Jpanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REAL ESTATE MANAGEMENT SYSTEM");
        Jpanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 570, 40));

        Fname.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Fname.setText("FirstName :");
        Jpanel2.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 30));

        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        Jpanel2.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 240, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Last Name :");
        Jpanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 30));
        Jpanel2.add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 240, 30));
        Jpanel2.add(Pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 240, 30));

        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        Jpanel2.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username :");
        Jpanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Password :");
        Jpanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, 30));

        Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1ActionPerformed(evt);
            }
        });
        Jpanel2.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 240, 30));

        Password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password2ActionPerformed(evt);
            }
        });
        Jpanel2.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 240, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Confirm Password :");
        Jpanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 140, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Phone Number :");
        Jpanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Select Account Type:");
        Jpanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 150, 30));
        Jpanel2.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 240, 50));

        Confirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Confirm.setText("Confirm");
        Jpanel2.add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, 30));

        Cancel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cancel1.setText("Cancel");
        Jpanel2.add(Cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 80, 30));

        getContentPane().add(Jpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1ActionPerformed

        
    }//GEN-LAST:event_Password1ActionPerformed

    private void Password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password2ActionPerformed

       
    }//GEN-LAST:event_Password2ActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel1;
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel Fname;
    private javax.swing.JPanel Jpanel2;
    private javax.swing.JTextField LName;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JTextField Pnumber;
    private javax.swing.JTextField User;
    private java.awt.Choice choice1;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
